import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/landingPage/Header'
import Main from '@/components/landingPage/Main'


export default function Home() {
  return (
    <>
      <Head>
        <title>U Pay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.layoutMain}>
            <div className={styles.layoutContainer}>
                <div className={styles.layoutContainerBg}></div>
                <Header />
               <Main />
            </div>
        </div>
    </>
  )
}
